/* Autogenerated by GenImageTool */

#include "test3.h"

const uint16_t GFX_PAL_1[16] =
{
    0x0E0E,
    0x0E20,
    0x0EEE,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000
};

const uint32_t GFX_TILESET_1[GFX_TILESET_1_TILE_COUNT][8] =
{
    {
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111
    },
    {
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222
    }
};

const uint16_t GFX_TILEMAPARRAY_1[GFX_TILEMAPARRAY_1_TILEMAP_COUNT][GFX_TILEMAPARRAY_1_TILE_COUNT] =
{
    {
        0x0000, 0x0000,
        0x0000, 0x0000
    },
    {
        0x0001, 0x0001,
        0x0001, 0x0001
    }
};

const uint16_t GFX_BLOCKMAP_1[GFX_BLOCKMAP_1_BLOCK_COUNT] =
{
    0x0000, 0x0001, 0x0000, 0x0001,
    0x0001, 0x0000, 0x0001, 0x0000
};

const uint8_t GFX_BLOCKMAP_2[GFX_BLOCKMAP_2_BLOCK_COUNT] =
{
    0x00, 0x01, 0x00, 0x01,
    0x01, 0x00, 0x01, 0x00
};
