/* Autogenerated by GenImageTool */

#include "test2.h"

const uint16_t GFX_PAL_1[16] =
{
    0x0e0e,
    0x0eee,
    0x0e20,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000
};

const uint32_t GFX_TILESET_1[GFX_TILESET_1_TILE_COUNT][8] =
{
    {
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111
    },
    {
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222
    }
};


const uint16_t GFX_TILEMAP_ARRAY_1[GFX_TILEMAP_ARRAY_1_TILEMAP_COUNT][GFX_TILEMAP_ARRAY_1_TILE_COUNT] =
{
    {
        0, 1,
        1, 1
    },
    {
        1, 0,
        1, 1
    },
    {
        1, 1,
        1, 0
    },
    {
        1, 1,
        0, 1
    }
};


const uint16_t GFX_SPRITE_ARRAY_1[GFX_SPRITE_ARRAY_1_SPRITE_COUNT][GFX_SPRITE_ARRAY_1_TILE_COUNT] =
{
    {
        0, 1,
        1, 1
    },
    {
        1, 1,
        0, 1
    },
    {
        1, 1,
        1, 0
    },
    {
        1, 0,
        1, 1
    }
};
