/* Autogenerated by GenImageTool */

#ifndef TEST4_H
#define TEST4_H

#include <genesis.h>

extern const uint16_t GFX_PAL_1[16];

extern const uint16_t GFX_PAL_2[16];

extern const uint16_t GFX_PAL_3[16];

extern const uint16_t GFX_PAL_4[16];

#define GFX_TILESET_1_TILE_COUNT 1
extern const uint32_t GFX_TILESET_1[GFX_TILESET_1_TILE_COUNT][8];

#define GFX_TILESET_2_TILE_COUNT 4
extern const uint32_t GFX_TILESET_2[GFX_TILESET_2_TILE_COUNT][8];

#define GFX_TILEMAP_1_TILE_WIDTH 2
#define GFX_TILEMAP_1_TILE_HEIGHT 2
#define GFX_TILEMAP_1_PIXEL_WIDTH 16
#define GFX_TILEMAP_1_PIXEL_HEIGHT 16
#define GFX_TILEMAP_1_TILE_COUNT 4
extern const uint16_t GFX_TILEMAP_1[GFX_TILEMAP_1_TILE_COUNT];

#endif
