/* Autogenerated by GenImageTool */

#include "test1.h"

const uint16_t GFX_PAL_1[16] =
{
    0x0e0e,
    0x000e,
    0x00e0,
    0x0e00,
    0x0eee,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000
};

const uint32_t GFX_TILESET_1[GFX_TILESET_1_TILE_COUNT][8] =
{
    {
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111
    },
    {
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222
    },
    {
        0x33333333,
        0x33333333,
        0x33333333,
        0x33333333,
        0x33333333,
        0x33333333,
        0x33333333,
        0x33333333
    },
    {
        0x44444444,
        0x44444444,
        0x44444444,
        0x44444444,
        0x44444444,
        0x44444444,
        0x44444444,
        0x44444444
    }
};

const uint16_t GFX_TILEMAP_1[GFX_TILEMAP_1_TILE_COUNT] =
{
    0, 1,
    2, 3
};

const uint16_t GFX_SPRITE_1[GFX_SPRITE_1_TILE_COUNT] =
{
    0, 2,
    1, 3
};
