/* Autogenerated by GenImageTool */

#include "test3.h"

const uint16_t GFX_PAL_1[16] =
{
    0x0e0e,
    0x0e20,
    0x0eee,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000
};

const uint32_t GFX_TILESET_1[GFX_TILESET_1_TILE_COUNT][8] =
{
    {
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111,
        0x11111111
    },
    {
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222,
        0x22222222
    }
};

const uint16_t GFX_TILEMAPARRAY_1[GFX_TILEMAPARRAY_1_TILEMAP_COUNT][GFX_TILEMAPARRAY_1_TILE_COUNT] =
{
    {
        0, 0,
        0, 0
    },
    {
        1, 1,
        1, 1
    }
};

const uint16_t GFX_BLOCKMAP_1[GFX_BLOCKMAP_1_BLOCK_COUNT] =
{
    0, 1, 0, 1,
    1, 0, 1, 0
};

const uint8_t GFX_BLOCKMAP_2[GFX_BLOCKMAP_2_BLOCK_COUNT] =
{
    0, 1, 0, 1,
    1, 0, 1, 0
};
