#ifndef MUSTACHE_TEMPLATES_HPP
#define MUSTACHE_TEMPLATES_HPP

constexpr const char* COLORS_TAG = "COLORS";
constexpr const char* COLOR_TAG = "COLOR";
constexpr const char* HEADER_FILENAME_TAG = "HEADER_FILENAME";
constexpr const char* INCLUDE_GUARD_TAG = "INCLUDE_GUARD";
constexpr const char* ISLAST_TAG = "ISLAST";
constexpr const char* NAME_TAG = "NAME";
constexpr const char* PALETTES_TAG = "PALETTES";
constexpr const char* PIXEL_HEIGHT_TAG = "PIXEL_HEIGHT";
constexpr const char* PIXEL_WIDTH_TAG = "PIXEL_WIDTH";
constexpr const char* ROW_TAG = "ROW";
constexpr const char* ROWS_TAG = "ROWS";
constexpr const char* TILE_COUNT_TAG = "TILE_COUNT";
constexpr const char* TILE_HEIGHT_TAG = "TILE_HEIGHT";
constexpr const char* TILE_WIDTH_TAG = "TILE_WIDTH";
constexpr const char* TILEMAPS_TAG = "TILEMAPS";
constexpr const char* TILES_TAG = "TILES";
constexpr const char* TILESETS_TAG = "TILESETS";

constexpr const char* C_FILE_TEMPLATE = R"(/* Autogenerated by GenImageTool */

#include "{{HEADER_FILENAME}}"
{{#PALETTES}}{{> c_palette}}{{/PALETTES}}
{{#TILESETS}}{{> c_tileset}}{{/TILESETS}}
{{#TILEMAPS}}{{> c_tilemap}}{{/TILEMAPS}}
)";



constexpr const char* C_PALETTE_TEMPLATE = R"(

const u16 {{NAME}}[16] =
{
{{#COLORS}}
{{> indent}}0x{{COLOR}}{{^ISLAST}},{{/ISLAST}}
{{/COLORS}}
};
)";



constexpr const char* C_SPRITE_TEMPLATE = R"(

const u16 {{NAME}}[{{NAME}}_TILE_COUNT] =
{
{{#ROWS}}
{{> indent}}{{ROW}}
{{/ROWS}}
};
)";



constexpr const char* C_TILEMAP_TEMPLATE = R"(

const u16 {{NAME}}[{{NAME}}_TILE_COUNT] =
{
{{#ROWS}}
{{> indent}}{{ROW}}
{{/ROWS}}
};
)";



constexpr const char* C_TILESET_TEMPLATE = R"(

const u32 {{NAME}}[{{NAME}}_TILE_COUNT][8] =
{
{{#TILES}}
{{> indent}}{
{{#ROWS}}
{{> indent}}{{> indent}}0x{{ROW}}{{^ISLAST}},{{/ISLAST}}
{{/ROWS}}
{{> indent}}}{{^ISLAST}},{{/ISLAST}}
{{/TILES}}
};
)";



constexpr const char* H_FILE_TEMPLATE = R"(/* Autogenerated by GenImageTool */

#ifndef {{INCLUDE_GUARD}}
#define {{INCLUDE_GUARD}}

#include <genesis.h>
{{#PALETTES}}{{> h_palette}}{{/PALETTES}}
{{#TILESETS}}{{> h_tileset}}{{/TILESETS}}
{{#TILEMAPS}}{{> h_tilemap}}{{/TILEMAPS}}

#endif
)";



constexpr const char* H_PALETTE_TEMPLATE = R"(

extern const u16 {{NAME}}[16];
)";



constexpr const char* H_SPRITE_TEMPLATE = R"(

#define {{NAME}}_TILE_WIDTH {{TILE_WIDTH}}
#define {{NAME}}_TILE_HEIGHT {{TILE_HEIGHT}}
#define {{NAME}}_PIXEL_WIDTH {{PIXEL_WIDTH}}
#define {{NAME}}_PIXEL_HEIGHT {{PIXEL_HEIGHT}}
#define {{NAME}}_TILE_COUNT {{TILE_COUNT}}
extern const u16 {{NAME}}[{{NAME}}_TILE_COUNT];
)";



constexpr const char* H_TILEMAP_TEMPLATE = R"(

#define {{NAME}}_TILE_WIDTH {{TILE_WIDTH}}
#define {{NAME}}_TILE_HEIGHT {{TILE_HEIGHT}}
#define {{NAME}}_PIXEL_WIDTH {{PIXEL_WIDTH}}
#define {{NAME}}_PIXEL_HEIGHT {{PIXEL_HEIGHT}}
#define {{NAME}}_TILE_COUNT {{TILE_COUNT}}
extern const u16 {{NAME}}[{{NAME}}_TILE_COUNT];
)";



constexpr const char* H_TILESET_TEMPLATE = R"(

#define {{NAME}}_TILE_COUNT {{TILE_COUNT}}
extern const u32 {{NAME}}[{{NAME}}_TILE_COUNT][8];
)";

constexpr const char* INDENT_TEMPLATE = "    ";

#endif
